name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JaCoCo HTML report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-html-report
        path: ${{ github.worspace }}target/site/jacoco/index.html
        
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.11.0
            
