name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with JaCoCo
      run: mvn test

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    # Upload JaCoCo HTML report
    - name: Upload JaCoCo HTML report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-html-report
        path: target/site/jacoco/index.html

    # Install jacoco-badge-generator
    - name: Install jacoco-badge-generator
      run: npm install -g jacoco-badge-generator

    # Generate coverage badge
    - name: Generate Coverage Badge
      run: |
        jacoco-badge-generator \
          --input target/site/jacoco/jacoco.xml \
          --output coverage-badge.svg \
          --title "Code Coverage" \
          --description "Coverage Badge"

    # Upload the coverage badge
    - name: Upload Coverage Badge
      uses: actions/upload-artifact@v2
      with:
        name: coverage-badge
        path: coverage-badge.svg

